import 'package:cloud_firestore/cloud_firestore.dart';

class FilterService {
  static final List<String> _dangerWords = [
    'c31k',
    'pompalı',
    'pompali',
    'tetikçi',
    'tetikci',
    'suikast',
    'infaz',
    'katil',
    'mermi',
    'kurşun',
    'kursun',
    'tetik düşür',
    'tetik dusur',
    'namlu',
    'susturucu',
    'kalemini kır',
    'kalemini kir',
    'paketleme',
    'paketle',
    'indirme',
    'indir',
    'temize çek',
    'temizle',
    'can alma',
    'can borcu',
    'fişek',
    'fisek',
    'patlar',
    'sıkma',
    'sikma',
    'ölüm listesi',
    'baskın',
    'baskin',
    'kaos',
    'korku sal',
    'katliam',
    'vahşet',
    'vahset',
    'kan dök',
    'kargaşa',
    'panik',
    'çatışma',
    'operasyon',
    'sabotaj',
    'mühimmat',
    'patlayıcı',
    'çökme',
    'cokme',
    'haraç',
    'harac',
    'tahsilat',
    'diz çöktür',
    'diz coktur',
    'gözdağı',
    'gozdagi',
    'mekan bas',
    'adres patlat',
    'kurşunla',
    'kursunla',
    'tehdit',
    'racon',
    'mafya',
    'çete',
    'cete',
    'fedai',
    'mücahit',
    'mucahit',
    'infazcı',
    'infazci',
    'uyusturucu',
    'eroin',
    'kokain',
    'esrar',
    'bonzai',
    'metamfetamin',
    'torbaci',
    'kenevir',
    'extacy',
    'peynir',
    'şeker',
    'seker',
    'mal',
    'fişeklik',
    'gramlık',
    'pkk',
    'fetö',
    'feto',
    'isid',
    'militan',
    'orgut',
    'suclu',
    'şeriat',
    'seriat',
    'hilafet',
    'cihad',
    'cihat',
    'kafir',
    'mürted',
    'murted',
    'takfir',
    'kelle',
    'kafa kes',
    'bomba',
    'patlat',
    'eylem',
    'hücre',
    'hucre',
    'biat',
    'taliban',
    'el kaide',
    'darbe',
    'ihtilal',
    'ayaklanma',
    'isyan',
    'molotof',
    'kaleşnikof',
    'keleş',
    'bahis',
    'kumar',
    'iddaa',
    'escort',
    'jigolo',
    'fuhus',
    'skandal',
    'leaked',
    'icraat',
    'hesap kes',
    'fişini çek',
    'fisini cek',
    'paket yap',
    'mevzu',
    'çatış',
    'catis',
    'had bildirme',
    'sustur',
    'ortadan kaldır',
    'ortadan kaldir',
    'bitir işini',
    'infaz timi',
    'sorgu paneli',
    'mernis',
    'data satışı',
    'tc sorgu',
    'gsm sorgu',
    'adres sorgu',
    'panelci',
    'hesap patlat',
    'kiralık hesap',
    'kiralik iban',
    'kiralik papara',
    'papara kirala',
    'iban kirala',
    'vurgun',
    'sazan sarmalı',
    'phishing',
    'oltalama',
    'cc basma',
    'cc satışı',
    'emanet var',
    'oyuncak var',
    'ısırır',
    'isirir',
    'demir var',
    'soğuk demir',
    'soguk demir',
    'kristal',
    'metin geldi',
    'meltem var',
    'meryem ana',
    'buz var',
    'tina',
    'pikaçu',
    'cam var',
    'ateş buz',
    'pudra',
    'toz şeker',
    'toz seker',
    'taş var',
    'tas var',
    'nevale',
    'derman',
    'vitamin',
    'yayılım',
    'sızma',
    'full paket',
    'vıp sorgu',
    'vip sorgu',
    'güncel data',
    'zula',
    'mekan patlat',
    'aklama',
    'havuz',
    'temizleme',
    'drop var',
    'torbacı',
    'ayakçı',
    'paketçi',
    'motorlu kurye',
    'adrese teslim',
    'servis var',
    'stok güncel',
    'stok yenilendi',
    'lokasyon at',
    'konum at',
    'sıcak teslim',
    'elden teslim',
    'numune var',
    'kıyak var',
    'tezgah aktif',
    'nöbetçi eczane',
    'gececi kurye',
    'hızlı servis',
    'fişekçi',
    'mal geldi',
    'kuru var',
    'sulu var',
    'kuru sıkı',
    'kurusıkı',
    'sulu tarla',
    'kuru ot',
    'toz duman',
    'dumanlı',
    'üfleme',
    'ufleme',
    'kapak',
    'kova yap',
    'sarma hazır',
    'dalgıç',
    'dalgic',
    'içiciyiz',
    'iciciyiz',
    'boşlukta',
    'asansör',
    'on numara',
    'bitkisel',
    'sentetik',
    'mevzu var',
    'karıştırma',
    'karistirma',
    'harmanım',
    'harmanim',
    'çözme',
    'cozme',
    'lyrica',
    'regapen',
    'gerica',
    'galara',
    'contramal',
    'xanax',
    'sentetik ecza',
    'ifşa',
    'paylaşırım',
    'yayarım',
    'santaj',
    'şantaj',
    'rezil ederim',
    'videon var',
    'kara para',
    'karapara',
    'aklama',
    'yıkama',
    'temiz para',
    'usdt bozum',
    'bozum yapılır',
    'soğuk cüzdan',
    'kripto aktar',
    'sahte para',
    'kalpazan',
    'para basma',
    'sahte kimlik',
    'sahte ehliyet',
    'plaka sorgu',
    'aile sorgu',
    'kimlik fotokopisi',
    'panel aktif',
    'ddos',
    'botnet',
    'rat atma',
    'keylogger',
    'log satışı',
    'patlak hesap',
    'mıknatıs',
    'miknatis',
    'beyaz un',
    'kar',
    'pırıl',
    'piril',
    'fişekle',
    'posta koy',
    'haraca bağla',
    'haraca bagla',
    'çizik at',
    'cizik at',
    'delik deşik',
    'topuğuna sık',
    'topuguna sik',
    'imha',
    'temizlikçi',
    'temizlikci',
    'emanet hazır',
    'emanet hazir',
    'çakmak',
    'cakmak',
    'parlatıcı',
    'parlatici',
    'dumanla',
    'çekim var',
    'cekim var',
    'full mernis',
    'güncel panel',
    'guncel panel',
    'keylog',
    'stealer',
    'root',
    'shell',
    'exploit',
    'injection',
    'bypass',
    'scam page',
    'fake site',
    'dolandır',
    'tokatla',
    'çırp',
    'cirp',
    'yol',
    'kekle',
    'avla',
    'olta',
    'sazan',
    'çarpılma',
    'carpilma',
    'kara liste',
    'kara borsa',
    'organ nakli',
    'böbrek satılık',
    'bobrek satilik',
    'hile aktif',
    'wallhack',
    'aimbot',
    'speedhack',
    'envanter hack',
    'coin çalma',
    'cüzdan boşalt',
    'cuzdan bosalt',
    'seed phrase',
    'private key',
    'metamask çalma',
  ];

  static final RegExp _phoneRegex = RegExp(
    r'(?:\+90|0)?\s?[1-9](\d{2})\s?(\d{3})\s?(\d{2})\s?(\d{2})',
    caseSensitive: false,
  );

  static Future<void> checkAndReport(
    String text,
    String userId, {
    String? chatId,
  }) async {
    final String lowText = text.toLowerCase();
    String? reason;

    for (final word in _dangerWords) {
      if (lowText.contains(word)) {
        reason = 'Tehlikeli İçerik: $word';
        break;
      }
    }

    if (reason == null && _phoneRegex.hasMatch(text)) {
      reason = 'Telefon Numarası (Sayısal)';
    }

    if (reason == null &&
        lowText.contains('beşyüz') &&
        (lowText.contains('beş') || lowText.contains('sıfır'))) {
      reason = 'Telefon Numarası (Yazılı Şüpheli)';
    }

    if (reason != null) {
      _sendReport(userId, text, reason, chatId);
    }
  }

  static void _sendReport(
    String userId,
    String content,
    String reason,
    String? chatId,
  ) {
    FirebaseFirestore.instance
        .collection('security_reports')
        .add({
          'userId': userId,
          'content': content,
          'reason': reason,
          'chatId': chatId ?? 'Global/Secret',
          'timestamp': FieldValue.serverTimestamp(),
          'status': 'active_investigation',
        })
        .catchError((_) {});
  }

  static bool isForbiddenContext(String key, String text) => false;
}
